"""
Generates a self-hosted contribution stats card (SVG) in the profile's blue theme.

Replaces third-party analytics widgets that can (and do) go dark: the previous
activity graph started answering HTTP 402 "Payment required", leaving a broken
image on the profile. This one is generated by the repo's own workflow and
served from the repo's own `output` branch, so nothing outside can break it.

Usage: python generate_stats.py <github_username> <output_path>
"""

import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime

from generate_drift import fetch_contributions

ACCENT = "#0096ff"
ACCENT_DIM = "#004a99"
BG = "#0d1117"
MUTED = "#8b949e"
GRID = "#161b22"

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def fetch_profile(username, token=None):
    """Public profile counters. Degrades to an empty dict if unreachable."""
    headers = {"User-Agent": "drift-stats-generator"}
    if token:
        headers["Authorization"] = f"bearer {token}"
    try:
        req = urllib.request.Request(
            f"https://api.github.com/users/{username}", headers=headers)
        with urllib.request.urlopen(req, timeout=25) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except (urllib.error.URLError, ValueError, TimeoutError) as e:
        print(f"  profile fetch failed ({e}); continuing without it")
        return {}


def flatten_days(calendar):
    """Every real (dated) day, chronologically."""
    days = []
    for week in calendar["weeks"]:
        for day in week["contributionDays"]:
            if day.get("date"):
                days.append((datetime.strptime(day["date"], "%Y-%m-%d").date(),
                             int(day["contributionCount"])))
    days.sort(key=lambda d: d[0])
    return days


def streaks(days):
    """(current, longest). Today counting zero does not break a live streak —
    that is the same convention GitHub's own streak widgets use."""
    longest = run = 0
    for _, count in days:
        run = run + 1 if count > 0 else 0
        longest = max(longest, run)

    current = 0
    for i in range(len(days) - 1, -1, -1):
        _, count = days[i]
        if count > 0:
            current += 1
        elif i == len(days) - 1:
            continue  # today still has time on the clock
        else:
            break
    return current, longest


def weekly_series(calendar):
    """One total per calendar week, plus the month each week starts in."""
    series = []
    for week in calendar["weeks"]:
        dated = [d for d in week["contributionDays"] if d.get("date")]
        if not dated:
            continue
        total = sum(int(d["contributionCount"]) for d in dated)
        first = datetime.strptime(dated[0]["date"], "%Y-%m-%d").date()
        series.append((first, total))
    return series


def fmt(n):
    """1234 -> 1.2k, so a big number never blows out its column."""
    return f"{n / 1000:.1f}k".replace(".0k", "k") if n >= 1000 else str(n)


def generate_svg(calendar, profile, username):
    days = flatten_days(calendar)
    current, longest = streaks(days)
    series = weekly_series(calendar)
    total = calendar["totalContributions"]
    best_day = max((c for _, c in days), default=0)
    active_days = sum(1 for _, c in days if c > 0)

    W, H = 998, 268
    PAD = 26

    # ── Chart geometry ──
    CH_TOP = 122
    CH_BOT = 226
    CH_H = CH_BOT - CH_TOP
    CH_L = PAD
    CH_R = W - PAD
    CH_W = CH_R - CH_L

    peak = max((v for _, v in series), default=0) or 1
    n = max(len(series) - 1, 1)
    pts = []
    for i, (_, v) in enumerate(series):
        x = CH_L + (i / n) * CH_W
        y = CH_BOT - (v / peak) * CH_H
        pts.append((x, y))

    # Catmull-Rom -> cubic Bezier: a smooth curve that still hits every real
    # data point, unlike a plain quadratic smoothing pass.
    if len(pts) >= 2:
        d = [f"M {pts[0][0]:.1f},{pts[0][1]:.1f}"]
        for i in range(len(pts) - 1):
            p0 = pts[i - 1] if i > 0 else pts[i]
            p1, p2 = pts[i], pts[i + 1]
            p3 = pts[i + 2] if i + 2 < len(pts) else p2
            # A Catmull-Rom spline overshoots around sharp spikes, which here
            # would draw contributions below zero. Clamp to the chart band.
            c1 = (p1[0] + (p2[0] - p0[0]) / 6,
                  min(max(p1[1] + (p2[1] - p0[1]) / 6, CH_TOP), CH_BOT))
            c2 = (p2[0] - (p3[0] - p1[0]) / 6,
                  min(max(p2[1] - (p3[1] - p1[1]) / 6, CH_TOP), CH_BOT))
            d.append(f"C {c1[0]:.1f},{c1[1]:.1f} {c2[0]:.1f},{c2[1]:.1f} "
                     f"{p2[0]:.1f},{p2[1]:.1f}")
        line_d = " ".join(d)
    else:
        line_d = f"M {CH_L},{CH_BOT} L {CH_R},{CH_BOT}"
    area_d = f"{line_d} L {pts[-1][0]:.1f},{CH_BOT} L {pts[0][0]:.1f},{CH_BOT} Z"

    L = []
    L.append(f'<svg xmlns="http://www.w3.org/2000/svg" '
             f'viewBox="0 0 {W} {H}" width="{W}" height="{H}" '
             f'font-family="ui-monospace,SFMono-Regular,Menlo,Consolas,monospace">')

    L.append("<defs>")
    L.append(f'  <linearGradient id="area" x1="0" y1="0" x2="0" y2="1">')
    L.append(f'    <stop offset="0%" stop-color="{ACCENT}" stop-opacity=".45"/>')
    L.append(f'    <stop offset="100%" stop-color="{ACCENT}" stop-opacity="0"/>')
    L.append('  </linearGradient>')
    L.append('  <filter id="glow"><feGaussianBlur stdDeviation="2.5" result="b"/>')
    L.append('    <feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>')
    L.append('  <clipPath id="reveal">')
    L.append(f'    <rect x="{CH_L}" y="0" width="0" height="{H}">')
    L.append(f'      <animate attributeName="width" values="0;{CH_W};{CH_W}" '
             f'keyTimes="0;0.45;1" dur="9s" repeatCount="indefinite"/>')
    L.append('    </rect>')
    L.append('  </clipPath>')
    L.append("</defs>")

    L.append("<style>")
    L.append(f"  @keyframes kpi-in {{ 0% {{ opacity:0; transform:translateY(6px); }}"
             f" 12% {{ opacity:1; transform:translateY(0); }}"
             f" 100% {{ opacity:1; transform:translateY(0); }} }}")
    L.append(f"  @keyframes sweep {{ 0% {{ opacity:0; }} 4% {{ opacity:.5; }}"
             f" 45% {{ opacity:.5; }} 55% {{ opacity:0; }} 100% {{ opacity:0; }} }}")
    L.append("</style>")

    L.append(f'<rect width="{W}" height="{H}" rx="10" fill="{BG}"/>')
    L.append(f'<rect x=".5" y=".5" width="{W - 1}" height="{H - 1}" rx="10" '
             f'fill="none" stroke="{ACCENT}" stroke-opacity=".18"/>')

    # ── Header ──
    L.append(f'<text x="{PAD}" y="34" font-size="13" fill="{ACCENT}" '
             f'opacity=".85">{username} // contribution activity</text>')
    L.append(f'<text x="{W - PAD}" y="34" text-anchor="end" font-size="11" '
             f'fill="{MUTED}" opacity=".7">last 12 months</text>')
    L.append(f'<line x1="{PAD}" y1="46" x2="{W - PAD}" y2="46" '
             f'stroke="{ACCENT}" stroke-opacity=".15"/>')

    # ── KPI row ──
    kpis = [("contributions", fmt(total)),
            ("current streak", f"{current}d"),
            ("longest streak", f"{longest}d"),
            ("active days", str(active_days)),
            ("best day", str(best_day))]
    if profile.get("public_repos") is not None:
        kpis.append(("public repos", str(profile["public_repos"])))
    if profile.get("followers") is not None:
        kpis.append(("followers", str(profile["followers"])))

    slot = (W - PAD * 2) / len(kpis)
    for i, (label, value) in enumerate(kpis):
        cx = PAD + slot * i + slot / 2
        delay = i * 0.12
        # `backwards` or the KPI shows at full opacity through its stagger delay
        # and then snaps to invisible when the animation finally starts.
        L.append(f'<g style="animation:kpi-in 9s ease-out {delay:.2f}s infinite '
                 f'backwards">')
        L.append(f'  <text x="{cx:.0f}" y="82" text-anchor="middle" font-size="27" '
                 f'font-weight="700" fill="{ACCENT}" filter="url(#glow)">{value}</text>')
        L.append(f'  <text x="{cx:.0f}" y="99" text-anchor="middle" font-size="9.5" '
                 f'fill="{MUTED}" letter-spacing="1.2">{label.upper()}</text>')
        L.append('</g>')
        if i:
            L.append(f'<line x1="{PAD + slot * i:.0f}" y1="62" '
                     f'x2="{PAD + slot * i:.0f}" y2="98" stroke="{GRID}"/>')

    # ── Chart gridlines + month ticks ──
    for f in (0.0, 0.5, 1.0):
        gy = CH_BOT - CH_H * f
        L.append(f'<line x1="{CH_L}" y1="{gy:.0f}" x2="{CH_R}" y2="{gy:.0f}" '
                 f'stroke="{GRID}"/>')
    L.append(f'<text x="{CH_L}" y="{CH_TOP - 6}" font-size="9" fill="{MUTED}" '
             f'opacity=".6">peak {peak}/week</text>')

    seen = set()
    for i, (date, _) in enumerate(series):
        if date.month in seen:
            continue
        seen.add(date.month)
        x = CH_L + (i / n) * CH_W
        L.append(f'<line x1="{x:.0f}" y1="{CH_TOP}" x2="{x:.0f}" y2="{CH_BOT}" '
                 f'stroke="{GRID}" stroke-dasharray="2 4"/>')
        L.append(f'<text x="{x:.0f}" y="{CH_BOT + 16}" font-size="9" '
                 f'fill="{MUTED}" opacity=".65">{MONTHS[date.month - 1]}</text>')

    # ── Area + line, revealed left-to-right ──
    L.append('<g clip-path="url(#reveal)">')
    L.append(f'  <path d="{area_d}" fill="url(#area)"/>')
    L.append(f'  <path d="{line_d}" fill="none" stroke="{ACCENT}" '
             f'stroke-width="2" stroke-linejoin="round" stroke-linecap="round" '
             f'filter="url(#glow)"/>')
    L.append('</g>')

    # Marker riding the curve as it draws
    L.append(f'<circle r="3.5" fill="#ffffff" filter="url(#glow)" opacity="0">'
             f'<animateMotion dur="9s" repeatCount="indefinite" keyPoints="0;1;1" '
             f'keyTimes="0;0.45;1" calcMode="linear" path="{line_d}"/>'
             f'<animate attributeName="opacity" values="0;1;1;0;0" '
             f'keyTimes="0;0.03;0.43;0.5;1" dur="9s" repeatCount="indefinite"/>'
             f'</circle>')

    # Scanline that follows the reveal edge
    L.append(f'<rect y="{CH_TOP}" width="1.5" height="{CH_H}" fill="{ACCENT}" '
             f'opacity="0" style="animation:sweep 9s linear infinite">'
             f'<animate attributeName="x" values="{CH_L};{CH_R};{CH_R}" '
             f'keyTimes="0;0.45;1" dur="9s" repeatCount="indefinite"/></rect>')

    L.append(f'<line x1="{CH_L}" y1="{CH_BOT}" x2="{CH_R}" y2="{CH_BOT}" '
             f'stroke="{ACCENT_DIM}"/>')

    # "now" pulse on the newest week, so the live edge of the data is obvious
    nx, ny = pts[-1]
    L.append(f'<circle cx="{nx:.1f}" cy="{ny:.1f}" r="3" fill="{ACCENT}" '
             f'filter="url(#glow)">'
             f'<animate attributeName="r" values="3;5.5;3" dur="1.8s" '
             f'repeatCount="indefinite"/>'
             f'<animate attributeName="opacity" values="1;.45;1" dur="1.8s" '
             f'repeatCount="indefinite"/></circle>')
    # Labelled "this week", not "now": the newest bucket is a partial week, so
    # its dip is time-of-week, not a drop in activity.
    L.append(f'<text x="{nx - 8:.1f}" y="{max(ny - 10, CH_TOP + 9):.0f}" '
             f'text-anchor="end" font-size="9" fill="{ACCENT}" '
             f'opacity=".75">this week</text>')

    L.append("</svg>")
    return "\n".join(L)


def main():
    username = sys.argv[1] if len(sys.argv) > 1 else "kblankk"
    output = sys.argv[2] if len(sys.argv) > 2 else "dist/stats.svg"
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")

    print(f"Fetching contributions for {username}...")
    calendar = fetch_contributions(username, token)
    profile = fetch_profile(username, token)

    svg = generate_svg(calendar, profile, username)

    os.makedirs(os.path.dirname(output) or ".", exist_ok=True)
    with open(output, "w", encoding="utf-8") as f:
        f.write(svg)
    print(f"Stats card saved to {output}")


if __name__ == "__main__":
    main()
